const authRoutes = require("./authRoutes");
const userRoutes = require("./userRoutes");
const businessRoutes = require("./businessRoutes");
const barPageRoutes = require("./barPageRoutes");
const barTableRoutes = require("./barTableRoutes");
const tableClassificationRoutes = require("./tableClassificationRoutes");
const eventRoutes = require("./eventRoutes");
const postRoutes = require("./postRoutes");
module.exports = { authRoutes, userRoutes, businessRoutes, barPageRoutes,tableClassificationRoutes,barTableRoutes,eventRoutes, postRoutes };
